language: php

php:
  - 7.0
  - 7.1
  - nightly

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - mkdir -p build/logs

after_script:
  - php vendor/bin/coveralls -v